[Xorg_xf86vidmodeproto]
git-tree-sha1 = "c199ff71c3f40211da070e2ea14f007c6110a035"

    [[Xorg_xf86vidmodeproto.download]]
    sha256 = "ace580cc306dcce014350a03c4c13f1979bcdc62d6cd383a36224e2f30e74431"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xf86vidmodeproto_jll.jl/releases/download/Xorg_xf86vidmodeproto-v2.3.1+1/Xorg_xf86vidmodeproto.v2.3.1.any.tar.gz"
