# Autogenerated wrapper script for Xorg_xf86vidmodeproto_jll for any
JLLWrappers.@generate_wrapper_header("Xorg_xf86vidmodeproto")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
